# Generated by Django 4.1 on 2022-11-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_instructir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructir',
            new_name='Instructor',
        ),
    ]
