# Generated by Django 4.1 on 2022-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_instructir_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manana'), (2, 'Tarde'), (3, 'Noche')], null=True),
        ),
    ]
